### PR TITLE
Lecture 10 Uploaded

### PR DESCRIPTION
**Pull request by samadkoita**

### CODE REVIEW

**Comment by vihari** [comment]
Thanks, but why not put in the lecture10.tex and reopen the pull request?

**Comment by samadkoita** [comment]
I will have to add the source images and ref file, is that okay?

**Comment by vihari** [comment]
In that case, make a folder "Lecture10_tex".

**Comment by vihari** [comment]
@samadkoita Let me know when you have it, will merge it.

**Comment by samadkoita** [comment]
@vihari Done.

**Comment by vihari** [comment]
Done! Thanks.

**Pull request merged**
